### ISSUE TITLE
cant start msfconsole

### ISSUE THREAD

**Issue by mattias-ohlsson** [mattias-ohlsson/kali-live-build-virtualbox-guest-config#1]
```
msfconsole
/usr/share/metasploit-framework/config/boot.rb:4: warning: already initialized constant GEMFILE_EXTENSIONS
You did not specify how you would like Rails to report deprecation notices for your production environment, please set config.active_support.deprecation to :notify at config/environments/production.rb
/opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application/configuration.rb:115:in `read': No such file or directory - /opt/metasploit/apps/pro/ui/config/database.yml (Errno::ENOENT)
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application/configuration.rb:115:in `database_configuration'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/railtie.rb:84:in `block (2 levels) in <class:Railtie>'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:25:in `each'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/railtie.rb:80:in `block in <class:Railtie>'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `instance_exec'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `run'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `each'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `run_initializers'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:136:in `initialize!'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /usr/share/metasploit-framework/config/environment.rb:5:in `<top (required)>'
    from /usr/share/metasploit-framework/lib/fastlib.rb:374:in `require'
    from /usr/share/metasploit-framework/lib/fastlib.rb:374:in `require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:103:in `require_environment!'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:68:in `require_environment!'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:86:in `start'
    from /opt/metasploit/apps/pro/msf3/msfconsole:26:in `<main>'
```

**Comment by mattias-ohlsson** [comment]
# kali-linux-20140816-virtualbox-vm-se-amd64:

test1

```
dpkg -s metasploit | grep Version
Version: 4.10.0-2014081302-1kali0
service postgresql start
[ ok ] Starting PostgreSQL 9.1 database server: main.
service metasploit start
msfconsole
```

# kali-linux-1.0.8

test1

```
dpkg -s metasploit | grep Version
Version: 4.9.3-2014071601-1kali2
msfconsole
```

test 2

```
apt-get update ; apt-get dist-upgrade
dpkg -s metasploit | grep Version
Version: 4.10.0-2014081302-1kali0
msfconsole
/usr/share/metasploit-framework/config/boot.rb:4: warning: already initialized constant GEMFILE_EXTENSIONS
You did not specify how you would like Rails to report deprecation notices for your production environment, please set config.active_support.deprecation to :notify at config/environments/production.rb
/opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application/configuration.rb:115:in `read': No such file or directory - /opt/metasploit/apps/pro/ui/config/database.yml (Errno::ENOENT)
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application/configuration.rb:115:in `database_configuration'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/railtie.rb:84:in `block (2 levels) in <class:Railtie>'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:25:in `each'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/railtie.rb:80:in `block in <class:Railtie>'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `instance_exec'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `run'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `each'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `run_initializers'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:136:in `initialize!'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /usr/share/metasploit-framework/config/environment.rb:5:in `<top (required)>'
    from /usr/share/metasploit-framework/lib/fastlib.rb:374:in `require'
    from /usr/share/metasploit-framework/lib/fastlib.rb:374:in `require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:103:in `require_environment!'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:68:in `require_environment!'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:86:in `start'
    from /opt/metasploit/apps/pro/msf3/msfconsole:26:in `<main>'
```
